### PR TITLE
Correct NativeModule's class name to be imported in JS

### PR DESCRIPTION
**Pull request by prithsharma**
Remove unused variables.

### CODE REVIEW

**Comment by prithsharma** [comment]
Tests failing because of some error in Travis configuration probably.

**Comment by Kennytian** [comment]
Good job, @prithsharma

**Comment by prithsharma** [comment]
No problem, thanks.
@Kennytian can you see why the tests are failing?
And disable them if need some time to work on them.

**Comment by Kennytian** [comment]
I guest we dismiss .travis.yml file,  i add this right now

**Pull request merged**
